-- WS6 (2026-06-11) — persist SEO health crawl history.
--
-- These tables let us look at trends over time instead of just the latest
-- baseline snapshot. The existing seo_health_baseline keeps the LATEST
-- crawl as a single-row JSONB blob for diffing; these new tables append
-- one row per run + one row per issue per run, so we can answer:
--   "Did issues for /iv-therapy/glutathione/north-york appear or
--    disappear over the last 14 days?"
--
-- Run once in Supabase SQL Editor:
--   https://supabase.com/dashboard/project/qaqzwfnjajyejehmdvuw/sql/new
--
-- Scope: ONLY these two tables. No RLS (writes are service-role only,
-- matching the rest of the seo_health_* family). Idempotent: safe to
-- re-run.

CREATE TABLE IF NOT EXISTS public.seo_health_runs (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  layer           text NOT NULL,                  -- 'A_crawl' | 'B_gsc'
  started_at      timestamptz NOT NULL DEFAULT now(),
  finished_at     timestamptz,
  status          text NOT NULL DEFAULT 'started', -- 'started' | 'ok' | 'partial' | 'error'
  total_urls      int,
  crawled_urls    int,
  issue_count     int,
  duration_ms     int,
  truncated       boolean,
  error_message   text,
  meta            jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS seo_health_runs_started_at_idx
  ON public.seo_health_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS seo_health_runs_layer_started_at_idx
  ON public.seo_health_runs (layer, started_at DESC);

CREATE TABLE IF NOT EXISTS public.seo_health_findings (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id    bigint NOT NULL REFERENCES public.seo_health_runs(id) ON DELETE CASCADE,
  layer     text NOT NULL,
  url       text NOT NULL,
  type      text NOT NULL,
  detail    text,
  seen_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS seo_health_findings_run_id_idx
  ON public.seo_health_findings (run_id);
CREATE INDEX IF NOT EXISTS seo_health_findings_url_idx
  ON public.seo_health_findings (url);
CREATE INDEX IF NOT EXISTS seo_health_findings_type_layer_idx
  ON public.seo_health_findings (type, layer);
